### ISSUE TITLE
请问可以适配阿里云吗，感觉阿里云的节点会更多一些

### ISSUE THREAD

**Issue by yanshibin** [shimmeris/SCFProxy#11]
https://help.aliyun.com/document_detail/74798.html
按文档在阿里云新建API网关后，后段再建一样的云函数，入口改成阿里的了，还是会报错
Addon error: Traceback (most recent call last):
  File "client.py", line 28, in request
    flow.request = flow.request.make(
  File "/Users/vincent/.venv/lib/python3.9/site-packages/mitmproxy/net/http/request.py", line 131, in make
    req.url = url
  File "/Users/vincent/.venv/lib/python3.9/site-packages/mitmproxy/net/http/request.py", line 285, in url
    self.scheme, self.host, self.port, self.path = mitmproxy.net.http.url.parse(val)
  File "/Users/vincent/.venv/lib/python3.9/site-packages/mitmproxy/net/http/url.py", line 52, in parse
    raise ValueError("No hostname given")
ValueError: No hostname given

**Comment by shimmeris** [comment]
我认识的一个人尝试过，当时他提到的是在他尝试的 3 个小时内都是同一个 ip，不太适合去做代理。

至于报错，看上去似乎是 URL 有问题，确保一下 `scf_servers` 变量是一个包含字符串的列表，不是字符串。可以在第 27 行前打印 `scf_server` 变量看看是否为阿里云的网关。

**Comment by yanshibin** [comment]
确认过 scf_servers 里面的字符串是 list 格式，应该是不行。如果有人测试过IP没有变化的话 却是没办法当作简单的代理使用了
