### ISSUE TITLE
Task exception was never retrieved 很频繁

### ISSUE THREAD

**Issue by tomsux** [shimmeris/SCFProxy#21]
这个报错很频繁，超时设置了900，应该不是超时问题
socks5版本，运行环境ubuntu20.04

Task exception was never retrieved
future: <Task finished name='Task-4168' coro=<scf_handle() done, defined at /home/abc/app/csf_proxy/socks5/bridge.py:7> exception=AttributeError("'Conn' object has no attribute 'add'")>
Traceback (most recent call last):
  File "/home/abc/app/csf_proxy/socks5/bridge.py", line 23, in forward
    data = await src.read(4096)
  File "/home/abc/app/csf_proxy/socks5/models.py", line 21, in read
    return await self.reader.read(size)
  File "/usr/lib/python3.8/asyncio/streams.py", line 684, in read
    await self._wait_for_data('read')
  File "/usr/lib/python3.8/asyncio/streams.py", line 517, in _wait_for_data
    await self._waiter
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/abc/app/csf_proxy/socks5/bridge.py", line 16, in scf_handle
    await socks5_forward(client, bridge)
  File "/home/abc/app/csf_proxy/socks5/bridge.py", line 38, in socks5_forward
    await asyncio.gather(*tasks)
  File "/home/abc/app/csf_proxy/socks5/bridge.py", line 32, in forward
    print_time(f"{src.add} sends a ConnectionReset")
AttributeError: 'Conn' object has no attribute 'add'

**Comment by shimmeris** [comment]
已修复，请重新 pull
