### ISSUE TITLE
HTTP代理服务器返回430 Connection reset by peer，且出现频率非常高

### ISSUE THREAD

**Issue by AbelLin1214** [shimmeris/SCFProxy#33]
从8月初开始，HTTP代理服务器突然就废了，100个请求最多能有30个返回下面这堆东西
```
Traceback (most recent call last):
  File "/var/lang/python3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/var/lang/python3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/var/lang/python3/lib/python3.6/site-packages/urllib3/connection.py", line 344, in connect
    ssl_context=context)
  File "/var/lang/python3/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 347, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/var/lang/python3/lib/python3.6/ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "/var/lang/python3/lib/python3.6/ssl.py", line 808, in __init__
    self.do_handshake()
  File "/var/lang/python3/lib/python3.6/ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "/var/lang/python3/lib/python3.6/ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
    ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/runtime/python3/bootstrap.py", line 176, in handle
    ret = self.real_handler(event, context)
  File "/var/user/server.py", line 24, in main_handler
    r = http.request(**kwargs, retries=False, decode_content=False)
  File "/var/lang/python3/lib/python3.6/site-packages/urllib3/request.py", line 68, in request
    **urlopen_kw)
  File "/var/lang/python3/lib/python3.6/site-packages/urllib3/request.py", line 89, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/var/lang/python3/lib/python3.6/site-packages/urllib3/poolmanager.py", line 324, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/var/lang/python3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/var/lang/python3/lib/python3.6/site-packages/urllib3/util/retry.py", line 344, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/var/lang/python3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/var/lang/python3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/var/lang/python3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/var/lang/python3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/var/lang/python3/lib/python3.6/site-packages/urllib3/connection.py", line 344, in connect
    ssl_context=context)
  File "/var/lang/python3/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 347, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/var/lang/python3/lib/python3.6/ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "/var/lang/python3/lib/python3.6/ssl.py", line 808, in __init__
    self.do_handshake()
  File "/var/lang/python3/lib/python3.6/ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "/var/lang/python3/lib/python3.6/ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
    urllib3.exceptions.ProtocolError: (\'Connection aborted.\', ConnectionResetError(104, \'Connection reset by peer\'))
```

**Comment by shimmeris** [comment]
是针对特定网站出现这个情况吗，我测试是没有什么问题的

**Comment by AbelLin1214** [comment]
> 

腾讯云函数，大陆区域都有出现，测试地址：https://myip.ipip.net。我测了好几个https网站都会

**Comment by shimmeris** [comment]
ipip.net 目前应该有封禁腾讯云 ip 的策略，我也遇到过，但使用阿里云会没事。其他 https 网站能说明一下吗

**Comment by AbelLin1214** [comment]
许多招标网站会有这个问题，例如https://b2b.10086.cn/b2b/main/preIndex.html、https://www.jianyu360.cn/

**Comment by shimmeris** [comment]
Connection Refused 一般都因为网站封禁 ip 导致，通过换不常用区域或者云厂商应该能解决
