### ISSUE TITLE
不稳定，一直报： IPv6 not supported

### ISSUE THREAD

**Issue by vanxv** [shimmeris/SCFProxy#36]
2022-11-18 13:57:11 [ERROR] IPv6 not supported
Task exception was never retrieved
future: <Task cancelling name='Task-2' coro=<socks_handle() done, defined at /Users/xcy/temp/SCFProxy/SOCKS5/src/socks_client/socks5.py:14> exception=UnboundLocalError("local variable 'remote_addr' referenced before assignment")>
Traceback (most recent call last):
  File "/Users/xcy/temp/SCFProxy/SOCKS5/src/socks_client/socks5.py", line 20, in socks_handle
    remote_addr, port = await socks5_connect(client)
  File "/Users/xcy/temp/SCFProxy/SOCKS5/src/socks_client/socks5.py", line 96, in socks5_connect
    return remote_addr, port
UnboundLocalError: local variable 'remote_addr' referenced before assignment

**Comment by shimmeris** [comment]
暂时不支持 IPv6
